name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish Plugin
    runs-on: ubuntu-18.04
    container: gradle:jdk8
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          ORG_GRADLE_PROJECT_amplitudeExperimentApiKey: ${{ secrets.AMPLITUDE_EXPERIMENT_API_KEY }}
          ORG_GRADLE_PROJECT_environment: "PRODUCTION"
          ORG_GRADLE_PROJECT_iterativelyEnvironment: "PRODUCTION"
          ORG_GRADLE_PROJECT_segmentWriteKey: ${{ secrets.SEGMENT_WRITE_KEY }}
        run: ./gradlew publishPlugin
